import type { L10n, PlaceItem } from '../../domain/types';
import { variants } from './words';

/**
 * Thai places. RTGS romanisation as on road signs; the common English
 * spelling (Chonburi, Buriram, Pattaya) and spellings without spaces are
 * accepted as listed variants. German names equal the English ones.
 */

const PROVINCE: L10n = { de: 'Provinz (Changwat)', en: 'Province (changwat)' };

const prov = (slug: string, native: string, rtgs: string, en: string, tier: 1 | 2 | 3, extra: string[] = []): PlaceItem => ({
  id: `th:region:${slug}`,
  kind: 'region',
  native,
  translit: rtgs,
  names: { en, de: en },
  accepted: [
    ...variants(rtgs, [en, ...extra]),
    `${en} Province`,
    `Provinz ${en}`,
    `Changwat ${rtgs}`,
  ],
  countryId: 'TH',
  regionType: 'province',
  tier,
  hint: PROVINCE,
});

/** All 77 provinces (76 changwat plus Bangkok). */
export const PROVINCES: PlaceItem[] = [
  prov('bangkok', 'กรุงเทพมหานคร', 'Krung Thep Maha Nakhon', 'Bangkok', 1, ['Krung Thep']),
  prov('krabi', 'กระบี่', 'Krabi', 'Krabi', 1),
  prov('kanchanaburi', 'กาญจนบุรี', 'Kanchanaburi', 'Kanchanaburi', 1),
  prov('kalasin', 'กาฬสินธุ์', 'Kalasin', 'Kalasin', 3),
  prov('kamphaeng-phet', 'กำแพงเพชร', 'Kamphaeng Phet', 'Kamphaeng Phet', 3),
  prov('khon-kaen', 'ขอนแก่น', 'Khon Kaen', 'Khon Kaen', 1),
  prov('chanthaburi', 'จันทบุรี', 'Chanthaburi', 'Chanthaburi', 2),
  prov('chachoengsao', 'ฉะเชิงเทรา', 'Chachoengsao', 'Chachoengsao', 2),
  prov('chon-buri', 'ชลบุรี', 'Chon Buri', 'Chonburi', 1),
  prov('chai-nat', 'ชัยนาท', 'Chai Nat', 'Chai Nat', 3, ['Chainat']),
  prov('chaiyaphum', 'ชัยภูมิ', 'Chaiyaphum', 'Chaiyaphum', 3),
  prov('chumphon', 'ชุมพร', 'Chumphon', 'Chumphon', 2),
  prov('chiang-rai', 'เชียงราย', 'Chiang Rai', 'Chiang Rai', 1),
  prov('chiang-mai', 'เชียงใหม่', 'Chiang Mai', 'Chiang Mai', 1),
  prov('trang', 'ตรัง', 'Trang', 'Trang', 2),
  prov('trat', 'ตราด', 'Trat', 'Trat', 2),
  prov('tak', 'ตาก', 'Tak', 'Tak', 2),
  prov('nakhon-nayok', 'นครนายก', 'Nakhon Nayok', 'Nakhon Nayok', 3),
  prov('nakhon-pathom', 'นครปฐม', 'Nakhon Pathom', 'Nakhon Pathom', 2),
  prov('nakhon-phanom', 'นครพนม', 'Nakhon Phanom', 'Nakhon Phanom', 2),
  prov('nakhon-ratchasima', 'นครราชสีมา', 'Nakhon Ratchasima', 'Nakhon Ratchasima', 1, ['Korat', 'Khorat']),
  prov('nakhon-si-thammarat', 'นครศรีธรรมราช', 'Nakhon Si Thammarat', 'Nakhon Si Thammarat', 1),
  prov('nakhon-sawan', 'นครสวรรค์', 'Nakhon Sawan', 'Nakhon Sawan', 2),
  prov('nonthaburi', 'นนทบุรี', 'Nonthaburi', 'Nonthaburi', 2),
  prov('narathiwat', 'นราธิวาส', 'Narathiwat', 'Narathiwat', 3),
  prov('nan', 'น่าน', 'Nan', 'Nan', 2),
  prov('bueng-kan', 'บึงกาฬ', 'Bueng Kan', 'Bueng Kan', 3, ['Bungkan']),
  prov('buri-ram', 'บุรีรัมย์', 'Buri Ram', 'Buriram', 2),
  prov('pathum-thani', 'ปทุมธานี', 'Pathum Thani', 'Pathum Thani', 2),
  prov('prachuap-khiri-khan', 'ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'Prachuap Khiri Khan', 2),
  prov('prachin-buri', 'ปราจีนบุรี', 'Prachin Buri', 'Prachinburi', 3),
  prov('pattani', 'ปัตตานี', 'Pattani', 'Pattani', 3),
  prov('phra-nakhon-si-ayutthaya', 'พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'Ayutthaya', 1),
  prov('phayao', 'พะเยา', 'Phayao', 'Phayao', 3),
  prov('phang-nga', 'พังงา', 'Phang Nga', 'Phang Nga', 2),
  prov('phatthalung', 'พัทลุง', 'Phatthalung', 'Phatthalung', 3, ['Phattalung']),
  prov('phichit', 'พิจิตร', 'Phichit', 'Phichit', 3),
  prov('phitsanulok', 'พิษณุโลก', 'Phitsanulok', 'Phitsanulok', 1),
  prov('phetchaburi', 'เพชรบุรี', 'Phetchaburi', 'Phetchaburi', 2, ['Phetburi']),
  prov('phetchabun', 'เพชรบูรณ์', 'Phetchabun', 'Phetchabun', 2),
  prov('phrae', 'แพร่', 'Phrae', 'Phrae', 3),
  prov('phuket', 'ภูเก็ต', 'Phuket', 'Phuket', 1),
  prov('maha-sarakham', 'มหาสารคาม', 'Maha Sarakham', 'Maha Sarakham', 3),
  prov('mukdahan', 'มุกดาหาร', 'Mukdahan', 'Mukdahan', 3),
  prov('mae-hong-son', 'แม่ฮ่องสอน', 'Mae Hong Son', 'Mae Hong Son', 2),
  prov('yasothon', 'ยโสธร', 'Yasothon', 'Yasothon', 3),
  prov('yala', 'ยะลา', 'Yala', 'Yala', 3),
  prov('roi-et', 'ร้อยเอ็ด', 'Roi Et', 'Roi Et', 3),
  prov('ranong', 'ระนอง', 'Ranong', 'Ranong', 3),
  prov('rayong', 'ระยอง', 'Rayong', 'Rayong', 2),
  prov('ratchaburi', 'ราชบุรี', 'Ratchaburi', 'Ratchaburi', 2),
  prov('lop-buri', 'ลพบุรี', 'Lop Buri', 'Lopburi', 2),
  prov('lampang', 'ลำปาง', 'Lampang', 'Lampang', 2),
  prov('lamphun', 'ลำพูน', 'Lamphun', 'Lamphun', 3),
  prov('loei', 'เลย', 'Loei', 'Loei', 2),
  prov('si-sa-ket', 'ศรีสะเกษ', 'Si Sa Ket', 'Sisaket', 3, ['Si Saket']),
  prov('sakon-nakhon', 'สกลนคร', 'Sakon Nakhon', 'Sakon Nakhon', 3),
  prov('songkhla', 'สงขลา', 'Songkhla', 'Songkhla', 1),
  prov('satun', 'สตูล', 'Satun', 'Satun', 3),
  prov('samut-prakan', 'สมุทรปราการ', 'Samut Prakan', 'Samut Prakan', 2),
  prov('samut-songkhram', 'สมุทรสงคราม', 'Samut Songkhram', 'Samut Songkhram', 3),
  prov('samut-sakhon', 'สมุทรสาคร', 'Samut Sakhon', 'Samut Sakhon', 3),
  prov('sa-kaeo', 'สระแก้ว', 'Sa Kaeo', 'Sa Kaeo', 3, ['Sa Kaew']),
  prov('saraburi', 'สระบุรี', 'Saraburi', 'Saraburi', 2),
  prov('sing-buri', 'สิงห์บุรี', 'Sing Buri', 'Sing Buri', 3),
  prov('sukhothai', 'สุโขทัย', 'Sukhothai', 'Sukhothai', 2),
  prov('suphan-buri', 'สุพรรณบุรี', 'Suphan Buri', 'Suphan Buri', 2),
  prov('surat-thani', 'สุราษฎร์ธานี', 'Surat Thani', 'Surat Thani', 1),
  prov('surin', 'สุรินทร์', 'Surin', 'Surin', 3),
  prov('nong-khai', 'หนองคาย', 'Nong Khai', 'Nong Khai', 2),
  prov('nong-bua-lam-phu', 'หนองบัวลำภู', 'Nong Bua Lam Phu', 'Nong Bua Lamphu', 3),
  prov('ang-thong', 'อ่างทอง', 'Ang Thong', 'Ang Thong', 3),
  prov('amnat-charoen', 'อำนาจเจริญ', 'Amnat Charoen', 'Amnat Charoen', 3),
  prov('udon-thani', 'อุดรธานี', 'Udon Thani', 'Udon Thani', 1),
  prov('uttaradit', 'อุตรดิตถ์', 'Uttaradit', 'Uttaradit', 3),
  prov('uthai-thani', 'อุทัยธานี', 'Uthai Thani', 'Uthai Thani', 3),
  prov('ubon-ratchathani', 'อุบลราชธานี', 'Ubon Ratchathani', 'Ubon Ratchathani', 1),
];

const city = (slug: string, native: string, rtgs: string, en: string, province: string, tier: 1 | 2 | 3, extra: string[] = [], hint?: L10n): PlaceItem => ({
  id: `th:city:${slug}`,
  kind: 'city',
  native,
  translit: rtgs,
  names: { en, de: en },
  accepted: variants(rtgs, [en, ...extra]),
  countryId: 'TH',
  regionId: `th:region:${province}`,
  tier,
  hint,
});

export const CITIES: PlaceItem[] = [
  city('bangkok', 'กรุงเทพมหานคร', 'Krung Thep Maha Nakhon', 'Bangkok', 'bangkok', 1, ['Krung Thep'], { de: 'Hauptstadt Thailands', en: 'Capital of Thailand' }),
  city('chiang-mai', 'เชียงใหม่', 'Chiang Mai', 'Chiang Mai', 'chiang-mai', 1, [], { de: 'Größte Stadt des Nordens', en: 'Largest city in the north' }),
  city('phuket', 'ภูเก็ต', 'Phuket', 'Phuket', 'phuket', 1, [], { de: 'Insel und Stadt an der Andamanensee', en: 'Island and town on the Andaman Sea' }),
  city('khon-kaen', 'ขอนแก่น', 'Khon Kaen', 'Khon Kaen', 'khon-kaen', 1, [], { de: 'Zentrum des Isan', en: 'Hub of Isan' }),
  city('nakhon-ratchasima', 'นครราชสีมา', 'Nakhon Ratchasima', 'Nakhon Ratchasima', 'nakhon-ratchasima', 1, ['Korat', 'Khorat'], { de: 'Tor zum Isan, kurz Korat', en: 'Gateway to Isan, known as Korat' }),
  city('hat-yai', 'หาดใหญ่', 'Hat Yai', 'Hat Yai', 'songkhla', 1, ['Haad Yai'], { de: 'Größte Stadt des Südens', en: 'Largest city in the south' }),
  city('udon-thani', 'อุดรธานี', 'Udon Thani', 'Udon Thani', 'udon-thani', 1, ['Udon']),
  city('pattaya', 'พัทยา', 'Phatthaya', 'Pattaya', 'chon-buri', 1, [], { de: 'Badeort am Golf von Thailand', en: 'Beach resort on the Gulf of Thailand' }),
  city('chiang-rai', 'เชียงราย', 'Chiang Rai', 'Chiang Rai', 'chiang-rai', 1, [], { de: 'Nördlichste Großstadt', en: 'Northernmost major city' }),
  city('ubon-ratchathani', 'อุบลราชธานี', 'Ubon Ratchathani', 'Ubon Ratchathani', 'ubon-ratchathani', 1, ['Ubon']),
  city('surat-thani', 'สุราษฎร์ธานี', 'Surat Thani', 'Surat Thani', 'surat-thani', 1, ['Surat']),
  city('phitsanulok', 'พิษณุโลก', 'Phitsanulok', 'Phitsanulok', 'phitsanulok', 2),
  city('nakhon-sawan', 'นครสวรรค์', 'Nakhon Sawan', 'Nakhon Sawan', 'nakhon-sawan', 2),
  city('nakhon-si-thammarat', 'นครศรีธรรมราช', 'Nakhon Si Thammarat', 'Nakhon Si Thammarat', 'nakhon-si-thammarat', 2),
  city('songkhla', 'สงขลา', 'Songkhla', 'Songkhla', 'songkhla', 2),
  city('hua-hin', 'หัวหิน', 'Hua Hin', 'Hua Hin', 'prachuap-khiri-khan', 1, [], { de: 'Königlicher Badeort', en: 'Royal beach resort' }),
  city('ayutthaya', 'อยุธยา', 'Ayutthaya', 'Ayutthaya', 'phra-nakhon-si-ayutthaya', 1, [], { de: 'Alte Königsstadt', en: 'Old royal capital' }),
  city('lampang', 'ลำปาง', 'Lampang', 'Lampang', 'lampang', 2),
  city('rayong', 'ระยอง', 'Rayong', 'Rayong', 'rayong', 2),
  city('chon-buri', 'ชลบุรี', 'Chon Buri', 'Chonburi', 'chon-buri', 2),
  city('si-racha', 'ศรีราชา', 'Si Racha', 'Si Racha', 'chon-buri', 2, ['Sriracha']),
  city('kanchanaburi', 'กาญจนบุรี', 'Kanchanaburi', 'Kanchanaburi', 'kanchanaburi', 1, [], { de: 'Brücke am Kwai', en: 'Bridge on the River Kwai' }),
  city('krabi', 'กระบี่', 'Krabi', 'Krabi', 'krabi', 1),
  city('trang', 'ตรัง', 'Trang', 'Trang', 'trang', 2),
  city('nakhon-pathom', 'นครปฐม', 'Nakhon Pathom', 'Nakhon Pathom', 'nakhon-pathom', 2),
  city('nonthaburi', 'นนทบุรี', 'Nonthaburi', 'Nonthaburi', 'nonthaburi', 2),
  city('pak-kret', 'ปากเกร็ด', 'Pak Kret', 'Pak Kret', 'nonthaburi', 3),
  city('samut-prakan', 'สมุทรปราการ', 'Samut Prakan', 'Samut Prakan', 'samut-prakan', 2),
  city('sukhothai', 'สุโขทัย', 'Sukhothai', 'Sukhothai', 'sukhothai', 2),
  city('mae-sot', 'แม่สอด', 'Mae Sot', 'Mae Sot', 'tak', 2, [], { de: 'Grenzstadt zu Myanmar', en: 'Border town to Myanmar' }),
  city('nong-khai', 'หนองคาย', 'Nong Khai', 'Nong Khai', 'nong-khai', 2, [], { de: 'Grenzstadt am Mekong, Brücke nach Laos', en: 'Border town on the Mekong, bridge to Laos' }),
  city('mukdahan', 'มุกดาหาร', 'Mukdahan', 'Mukdahan', 'mukdahan', 3),
  city('nakhon-phanom', 'นครพนม', 'Nakhon Phanom', 'Nakhon Phanom', 'nakhon-phanom', 3),
  city('sakon-nakhon', 'สกลนคร', 'Sakon Nakhon', 'Sakon Nakhon', 'sakon-nakhon', 3),
  city('roi-et', 'ร้อยเอ็ด', 'Roi Et', 'Roi Et', 'roi-et', 3),
  city('buri-ram', 'บุรีรัมย์', 'Buri Ram', 'Buriram', 'buri-ram', 3),
  city('surin', 'สุรินทร์', 'Surin', 'Surin', 'surin', 3),
  city('lop-buri', 'ลพบุรี', 'Lop Buri', 'Lopburi', 'lop-buri', 2),
  city('saraburi', 'สระบุรี', 'Saraburi', 'Saraburi', 'saraburi', 3),
  city('phetchaburi', 'เพชรบุรี', 'Phetchaburi', 'Phetchaburi', 'phetchaburi', 3, ['Phetburi']),
  city('ratchaburi', 'ราชบุรี', 'Ratchaburi', 'Ratchaburi', 'ratchaburi', 3),
  city('chanthaburi', 'จันทบุรี', 'Chanthaburi', 'Chanthaburi', 'chanthaburi', 3),
  city('trat', 'ตราด', 'Trat', 'Trat', 'trat', 3),
  city('chumphon', 'ชุมพร', 'Chumphon', 'Chumphon', 'chumphon', 2),
  city('ranong', 'ระนอง', 'Ranong', 'Ranong', 'ranong', 3),
  city('yala', 'ยะลา', 'Yala', 'Yala', 'yala', 3),
  city('pattani', 'ปัตตานี', 'Pattani', 'Pattani', 'pattani', 3),
  city('loei', 'เลย', 'Loei', 'Loei', 'loei', 3),
  city('nan', 'น่าน', 'Nan', 'Nan', 'nan', 3),
  city('mae-hong-son', 'แม่ฮ่องสอน', 'Mae Hong Son', 'Mae Hong Son', 'mae-hong-son', 3),

  // The remaining provincial capitals – each carries its province's name
  city('kalasin', 'กาฬสินธุ์', 'Kalasin', 'Kalasin', 'kalasin', 3),
  city('kamphaeng-phet', 'กำแพงเพชร', 'Kamphaeng Phet', 'Kamphaeng Phet', 'kamphaeng-phet', 3),
  city('chachoengsao', 'ฉะเชิงเทรา', 'Chachoengsao', 'Chachoengsao', 'chachoengsao', 2, ['Paet Rio']),
  city('chai-nat', 'ชัยนาท', 'Chai Nat', 'Chai Nat', 'chai-nat', 3, ['Chainat']),
  city('chaiyaphum', 'ชัยภูมิ', 'Chaiyaphum', 'Chaiyaphum', 'chaiyaphum', 3),
  city('tak', 'ตาก', 'Tak', 'Tak', 'tak', 3),
  city('nakhon-nayok', 'นครนายก', 'Nakhon Nayok', 'Nakhon Nayok', 'nakhon-nayok', 3),
  city('narathiwat', 'นราธิวาส', 'Narathiwat', 'Narathiwat', 'narathiwat', 3),
  city('bueng-kan', 'บึงกาฬ', 'Bueng Kan', 'Bueng Kan', 'bueng-kan', 3, ['Bung Kan', 'Buengkan'], { de: 'Am Mekong, jüngste Provinzhauptstadt', en: 'On the Mekong, the newest provincial capital' }),
  city('pathum-thani', 'ปทุมธานี', 'Pathum Thani', 'Pathum Thani', 'pathum-thani', 2),
  city('prachuap-khiri-khan', 'ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'Prachuap Khiri Khan', 'prachuap-khiri-khan', 3, ['Prachuap']),
  city('prachin-buri', 'ปราจีนบุรี', 'Prachin Buri', 'Prachinburi', 'prachin-buri', 3),
  city('phayao', 'พะเยา', 'Phayao', 'Phayao', 'phayao', 3),
  city('phang-nga', 'พังงา', 'Phang Nga', 'Phang Nga', 'phang-nga', 3, ['Phangnga']),
  city('phatthalung', 'พัทลุง', 'Phatthalung', 'Phatthalung', 'phatthalung', 3, ['Phattalung']),
  city('phichit', 'พิจิตร', 'Phichit', 'Phichit', 'phichit', 3),
  city('phetchabun', 'เพชรบูรณ์', 'Phetchabun', 'Phetchabun', 'phetchabun', 3),
  city('phrae', 'แพร่', 'Phrae', 'Phrae', 'phrae', 3),
  city('maha-sarakham', 'มหาสารคาม', 'Maha Sarakham', 'Maha Sarakham', 'maha-sarakham', 3, ['Mahasarakham']),
  city('yasothon', 'ยโสธร', 'Yasothon', 'Yasothon', 'yasothon', 3),
  city('lamphun', 'ลำพูน', 'Lamphun', 'Lamphun', 'lamphun', 3),
  city('si-sa-ket', 'ศรีสะเกษ', 'Si Sa Ket', 'Sisaket', 'si-sa-ket', 3, ['Srisaket']),
  city('satun', 'สตูล', 'Satun', 'Satun', 'satun', 3),
  city('samut-songkhram', 'สมุทรสงคราม', 'Samut Songkhram', 'Samut Songkhram', 'samut-songkhram', 3, ['Mae Klong', 'Maeklong']),
  city('samut-sakhon', 'สมุทรสาคร', 'Samut Sakhon', 'Samut Sakhon', 'samut-sakhon', 2, ['Mahachai', 'Maha Chai']),
  city('sa-kaeo', 'สระแก้ว', 'Sa Kaeo', 'Sa Kaeo', 'sa-kaeo', 3, ['Sa Kaew']),
  city('sing-buri', 'สิงห์บุรี', 'Sing Buri', 'Singburi', 'sing-buri', 3),
  city('suphan-buri', 'สุพรรณบุรี', 'Suphan Buri', 'Suphanburi', 'suphan-buri', 3),
  city('nong-bua-lam-phu', 'หนองบัวลำภู', 'Nong Bua Lam Phu', 'Nong Bua Lamphu', 'nong-bua-lam-phu', 3),
  city('ang-thong', 'อ่างทอง', 'Ang Thong', 'Ang Thong', 'ang-thong', 3),
  city('amnat-charoen', 'อำนาจเจริญ', 'Amnat Charoen', 'Amnat Charoen', 'amnat-charoen', 3),
  city('uttaradit', 'อุตรดิตถ์', 'Uttaradit', 'Uttaradit', 'uttaradit', 3),
  city('uthai-thani', 'อุทัยธานี', 'Uthai Thani', 'Uthai Thani', 'uthai-thani', 3),

  // The largest towns that are not provincial capitals
  city('khlong-luang', 'คลองหลวง', 'Khlong Luang', 'Khlong Luang', 'pathum-thani', 3, ['Klong Luang'], { de: 'Nördlich von Bangkok, Rangsit', en: 'North of Bangkok, Rangsit area' }),
  city('phra-pradaeng', 'พระประแดง', 'Phra Pradaeng', 'Phra Pradaeng', 'samut-prakan', 3),
  city('bang-kruai', 'บางกรวย', 'Bang Kruai', 'Bang Kruai', 'nonthaburi', 3, ['Bang Kruay']),
  city('krathum-baen', 'กระทุ่มแบน', 'Krathum Baen', 'Krathum Baen', 'samut-sakhon', 3),
  city('sattahip', 'สัตหีบ', 'Sattahip', 'Sattahip', 'chon-buri', 3, [], { de: 'Marinestützpunkt am Golf', en: 'Naval base on the Gulf' }),
  city('lam-luk-ka', 'ลำลูกกา', 'Lam Luk Ka', 'Lam Luk Ka', 'pathum-thani', 3),
  city('ban-pong', 'บ้านโป่ง', 'Ban Pong', 'Ban Pong', 'ratchaburi', 3),
  city('phra-phutthabat', 'พระพุทธบาท', 'Phra Phutthabat', 'Phra Phutthabat', 'saraburi', 3, ['Phra Buddhabat']),
  city('klaeng', 'แกลง', 'Klaeng', 'Klaeng', 'rayong', 3),
  city('ko-samui', 'เกาะสมุย', 'Ko Samui', 'Ko Samui', 'surat-thani', 2, ['Koh Samui', 'Samui'], { de: 'Ferieninsel im Golf von Thailand', en: 'Holiday island in the Gulf of Thailand' }),
  city('cha-am', 'ชะอำ', 'Cha-am', 'Cha-am', 'phetchaburi', 3, ['Cha am', 'Chaam']),
  city('pak-chong', 'ปากช่อง', 'Pak Chong', 'Pak Chong', 'nakhon-ratchasima', 3, [], { de: 'Am Khao-Yai-Nationalpark', en: 'At Khao Yai National Park' }),
  city('sadao', 'สะเดา', 'Sadao', 'Sadao', 'songkhla', 3, [], { de: 'Grenzübergang nach Malaysia', en: 'Border crossing to Malaysia' }),
  city('warin-chamrap', 'วารินชำราบ', 'Warin Chamrap', 'Warin Chamrap', 'ubon-ratchathani', 3),
  city('su-ngai-kolok', 'สุไหงโก-ลก', 'Su-ngai Kolok', 'Sungai Kolok', 'narathiwat', 3, ['Sungai Golok', 'Su-ngai Ko-lok'], { de: 'Grenzstadt zu Malaysia', en: 'Border town to Malaysia' }),
  city('betong', 'เบตง', 'Betong', 'Betong', 'yala', 3, [], { de: 'Südlichste Stadt Thailands', en: 'Southernmost town in Thailand' }),
  city('mae-sai', 'แม่สาย', 'Mae Sai', 'Mae Sai', 'chiang-rai', 3, [], { de: 'Nördlichster Punkt, Grenze zu Myanmar', en: 'Northernmost point, border to Myanmar' }),
];
