import type { L10n, PlaceItem } from '../../domain/types';

/**
 * Greek places: the 100 largest towns, counting the suburbs of Athens and
 * Thessaloniki as part of their city (Piraeus excepted), plus the 13 regions
 * and the large islands. Transliteration follows ELOT 743 as on road signs.
 */

const city = (
  slug: string,
  native: string,
  translit: string,
  en: string,
  de: string,
  regionSlug: string,
  tier: 1 | 2 | 3,
  extra: string[] = [],
  hint?: L10n,
): PlaceItem => ({
  id: `el:city:${slug}`,
  kind: 'city',
  native,
  translit,
  names: { de, en },
  accepted: [translit, en, de, ...extra],
  countryId: 'GR',
  regionId: `el:region:${regionSlug}`,
  tier,
  hint,
});


export const CITIES: PlaceItem[] = [
  city('athina', 'Αθήνα', 'Athina', 'Athens', 'Athen', 'attiki', 1, [], { de: 'Hauptstadt Griechenlands', en: 'Capital of Greece' }),
  city('thessaloniki', 'Θεσσαλονίκη', 'Thessaloniki', 'Thessaloniki', 'Thessaloniki', 'kentriki-makedonia', 1, ['Salonica', 'Saloniki', 'Salonika'], { de: 'Zweitgrößte Stadt, Hafen am Thermaischen Golf', en: 'Second city, port on the Thermaic Gulf' }),
  city('peiraias', 'Πειραιάς', 'Peiraias', 'Piraeus', 'Piräus', 'attiki', 1, ['Pireas', 'Piraeas', 'Piraus'], { de: 'Hafen Athens', en: 'Port of Athens' }),
  city('patra', 'Πάτρα', 'Patra', 'Patras', 'Patras', 'dytiki-ellada', 1, [], { de: 'Fährhafen nach Italien', en: 'Ferry port for Italy' }),
  city('irakleio', 'Ηράκλειο', 'Irakleio', 'Heraklion', 'Heraklion', 'kriti', 1, ['Iraklio', 'Iraklion', 'Heraklio', 'Herakleion'], { de: 'Größte Stadt Kretas', en: 'Largest city on Crete' }),
  city('larisa', 'Λάρισα', 'Larisa', 'Larissa', 'Larisa', 'thessalia', 1),
  city('volos', 'Βόλος', 'Volos', 'Volos', 'Volos', 'thessalia', 1, [], { de: 'Hafen am Pilion', en: 'Port below Mount Pelion' }),
  city('ioannina', 'Ιωάννινα', 'Ioannina', 'Ioannina', 'Ioannina', 'ipeiros', 1, [], { de: 'Hauptstadt des Epirus, am Pamvotida-See', en: 'Capital of Epirus, on Lake Pamvotida' }),
  city('chania', 'Χανιά', 'Chania', 'Chania', 'Chania', 'kriti', 1, ['Hania', 'Khania'], { de: 'Westkreta', en: 'Western Crete' }),
  city('kalamata', 'Καλαμάτα', 'Kalamata', 'Kalamata', 'Kalamata', 'peloponnisos', 1),
  city('kavala', 'Καβάλα', 'Kavala', 'Kavala', 'Kavala', 'anatoliki-makedonia-thraki', 1),
  city('alexandroupoli', 'Αλεξανδρούπολη', 'Alexandroupoli', 'Alexandroupolis', 'Alexandroupoli', 'anatoliki-makedonia-thraki', 1, [], { de: 'Nahe der Grenze zur Türkei', en: 'Near the Turkish border' }),
  city('serres', 'Σέρρες', 'Serres', 'Serres', 'Serres', 'kentriki-makedonia', 2),
  city('xanthi', 'Ξάνθη', 'Xanthi', 'Xanthi', 'Xanthi', 'anatoliki-makedonia-thraki', 2),
  city('komotini', 'Κομοτηνή', 'Komotini', 'Komotini', 'Komotini', 'anatoliki-makedonia-thraki', 2),
  city('katerini', 'Κατερίνη', 'Katerini', 'Katerini', 'Katerini', 'kentriki-makedonia', 2, [], { de: 'Am Fuß des Olymp', en: 'At the foot of Mount Olympus' }),
  city('trikala', 'Τρίκαλα', 'Trikala', 'Trikala', 'Trikala', 'thessalia', 2, [], { de: 'Nahe den Meteora-Klöstern', en: 'Near the Meteora monasteries' }),
  city('karditsa', 'Καρδίτσα', 'Karditsa', 'Karditsa', 'Karditsa', 'thessalia', 3),
  city('lamia', 'Λαμία', 'Lamia', 'Lamia', 'Lamia', 'sterea-ellada', 2, [], { de: 'An der Autobahn Athen–Thessaloniki', en: 'On the Athens–Thessaloniki motorway' }),
  city('chalkida', 'Χαλκίδα', 'Chalkida', 'Chalcis', 'Chalkida', 'sterea-ellada', 2, ['Chalkis', 'Halkida', 'Khalkida'], { de: 'Brücke nach Euböa', en: 'Bridge to Euboea' }),
  city('veroia', 'Βέροια', 'Veroia', 'Veria', 'Veria', 'kentriki-makedonia', 2, ['Verria', 'Veroia']),
  city('kozani', 'Κοζάνη', 'Kozani', 'Kozani', 'Kozani', 'dytiki-makedonia', 2),
  city('florina', 'Φλώρινα', 'Florina', 'Florina', 'Florina', 'dytiki-makedonia', 3, [], { de: 'Nahe der Grenze zu Nordmazedonien', en: 'Near the North Macedonian border' }),
  city('kastoria', 'Καστοριά', 'Kastoria', 'Kastoria', 'Kastoria', 'dytiki-makedonia', 3),
  city('drama', 'Δράμα', 'Drama', 'Drama', 'Drama', 'anatoliki-makedonia-thraki', 2),
  city('agrinio', 'Αγρίνιο', 'Agrinio', 'Agrinio', 'Agrinio', 'dytiki-ellada', 2),
  city('pyrgos', 'Πύργος', 'Pyrgos', 'Pyrgos', 'Pyrgos', 'dytiki-ellada', 3, [], { de: 'Nahe Olympia', en: 'Near Olympia' }),
  city('tripoli', 'Τρίπολη', 'Tripoli', 'Tripoli', 'Tripoli', 'peloponnisos', 2, ['Tripolis'], { de: 'Mitte der Peloponnes', en: 'Centre of the Peloponnese' }),
  city('korinthos', 'Κόρινθος', 'Korinthos', 'Corinth', 'Korinth', 'peloponnisos', 1, [], { de: 'Am Kanal von Korinth', en: 'At the Corinth Canal' }),
  city('nafplio', 'Ναύπλιο', 'Nafplio', 'Nafplio', 'Nafplio', 'peloponnisos', 2, ['Nafplion', 'Nauplia', 'Nauplion']),
  city('sparti', 'Σπάρτη', 'Sparti', 'Sparta', 'Sparta', 'peloponnisos', 2),
  city('rethymno', 'Ρέθυμνο', 'Rethymno', 'Rethymno', 'Rethymno', 'kriti', 2, ['Rethymnon']),
  city('agios-nikolaos', 'Άγιος Νικόλαος', 'Agios Nikolaos', 'Agios Nikolaos', 'Agios Nikolaos', 'kriti', 2, ['Ayios Nikolaos', 'Hagios Nikolaos'], { de: 'Ostkreta', en: 'Eastern Crete' }),
  city('mytilini', 'Μυτιλήνη', 'Mytilini', 'Mytilene', 'Mytilini', 'voreio-aigaio', 2, ['Mitilini'], { de: 'Hauptort von Lesbos', en: 'Main town of Lesbos' }),
  city('preveza', 'Πρέβεζα', 'Preveza', 'Preveza', 'Preveza', 'ipeiros', 3),
  city('igoumenitsa', 'Ηγουμενίτσα', 'Igoumenitsa', 'Igoumenitsa', 'Igoumenitsa', 'ipeiros', 2, [], { de: 'Fährhafen, Startpunkt der Egnatia Odos', en: 'Ferry port, start of the Egnatia Odos' }),
  city('arta', 'Άρτα', 'Arta', 'Arta', 'Arta', 'ipeiros', 3),
  city('mesolongi', 'Μεσολόγγι', 'Mesolongi', 'Missolonghi', 'Messolonghi', 'dytiki-ellada', 3, ['Messolongi', 'Mesolonghi', 'Missolongi']),
  city('thiva', 'Θήβα', 'Thiva', 'Thebes', 'Theben', 'sterea-ellada', 3),
  city('edessa', 'Έδεσσα', 'Edessa', 'Edessa', 'Edessa', 'kentriki-makedonia', 3),

  // Further towns up to the 100 largest
  city('ptolemaida', 'Πτολεμαΐδα', 'Ptolemaida', 'Ptolemaida', 'Ptolemaida', 'dytiki-makedonia', 2, ['Ptolemais'], { de: 'Braunkohlekraftwerke', en: 'Lignite power stations' }),
  city('giannitsa', 'Γιαννιτσά', 'Giannitsa', 'Giannitsa', 'Giannitsa', 'kentriki-makedonia', 2, ['Yiannitsa', 'Yannitsa']),
  city('kerkyra', 'Κέρκυρα', 'Kerkyra', 'Corfu', 'Korfu', 'ionia-nisia', 1, ['Kerkira'], { de: 'Hauptstadt der Insel Korfu', en: 'Main town of Corfu' }),
  city('chios', 'Χίος', 'Chios', 'Chios', 'Chios', 'voreio-aigaio', 2, ['Hios', 'Khios'], { de: 'Hauptort der Insel Chios', en: 'Main town of Chios' }),
  city('rodos', 'Ρόδος', 'Rodos', 'Rhodes', 'Rhodos', 'notio-aigaio', 1, [], { de: 'Hauptstadt der Insel Rhodos', en: 'Main town of Rhodes' }),
  city('megara', 'Μέγαρα', 'Megara', 'Megara', 'Megara', 'attiki', 2, [], { de: 'An der Autobahn Athen–Korinth', en: 'On the Athens–Corinth motorway' }),
  city('kilkis', 'Κιλκίς', 'Kilkis', 'Kilkis', 'Kilkis', 'kentriki-makedonia', 2),
  city('argos', 'Άργος', 'Argos', 'Argos', 'Argos', 'peloponnisos', 2),
  city('livadeia', 'Λιβαδειά', 'Livadeia', 'Livadeia', 'Livadia', 'sterea-ellada', 2, ['Livadia', 'Levadia']),
  city('artemida', 'Αρτέμιδα', 'Artemida', 'Artemida', 'Artemida', 'attiki', 3, ['Loutsa']),
  city('aigio', 'Αίγιο', 'Aigio', 'Aigio', 'Egio', 'dytiki-ellada', 2, ['Aegio', 'Aigion', 'Egio']),
  city('naousa', 'Νάουσα', 'Naousa', 'Naousa', 'Naoussa', 'kentriki-makedonia', 3, ['Naoussa']),
  city('kos', 'Κως', 'Kos', 'Kos', 'Kos', 'notio-aigaio', 2, [], { de: 'Hauptort der Insel Kos', en: 'Main town of Kos' }),
  city('amaliada', 'Αμαλιάδα', 'Amaliada', 'Amaliada', 'Amaliada', 'dytiki-ellada', 3),
  city('orestiada', 'Ορεστιάδα', 'Orestiada', 'Orestiada', 'Orestiada', 'anatoliki-makedonia-thraki', 3, [], { de: 'Nördlichste Stadt, nahe der Türkei', en: 'Northernmost town, near Turkey' }),
  city('nea-makri', 'Νέα Μάκρη', 'Nea Makri', 'Nea Makri', 'Nea Makri', 'attiki', 3),
  city('nafpaktos', 'Ναύπακτος', 'Nafpaktos', 'Nafpaktos', 'Nafpaktos', 'dytiki-ellada', 2, ['Navpaktos', 'Lepanto']),
  city('ierapetra', 'Ιεράπετρα', 'Ierapetra', 'Ierapetra', 'Ierapetra', 'kriti', 2, [], { de: 'Südküste Kretas', en: 'South coast of Crete' }),
  city('rafina', 'Ραφήνα', 'Rafina', 'Rafina', 'Rafina', 'attiki', 2, [], { de: 'Fährhafen östlich von Athen', en: 'Ferry port east of Athens' }),
  city('loutraki', 'Λουτράκι', 'Loutraki', 'Loutraki', 'Loutraki', 'peloponnisos', 3),
  city('zakynthos', 'Ζάκυνθος', 'Zakynthos', 'Zakynthos', 'Zakynthos', 'ionia-nisia', 2, ['Zante', 'Zakinthos'], { de: 'Hauptort der Insel Zakynthos', en: 'Main town of Zakynthos' }),
  city('ermoupoli', 'Ερμούπολη', 'Ermoupoli', 'Ermoupoli', 'Ermoupoli', 'notio-aigaio', 2, ['Ermoupolis', 'Hermoupolis'], { de: 'Hauptort von Syros', en: 'Main town of Syros' }),
  city('tyrnavos', 'Τύρναβος', 'Tyrnavos', 'Tyrnavos', 'Tyrnavos', 'thessalia', 3, ['Tirnavos']),
  city('grevena', 'Γρεβενά', 'Grevena', 'Grevena', 'Grevena', 'dytiki-makedonia', 3),
  city('farsala', 'Φάρσαλα', 'Farsala', 'Farsala', 'Farsala', 'thessalia', 3, ['Pharsala', 'Pharsalos']),
  city('polygyros', 'Πολύγυρος', 'Polygyros', 'Polygyros', 'Polygyros', 'kentriki-makedonia', 3, ['Poligiros', 'Polygiros']),
  city('argostoli', 'Αργοστόλι', 'Argostoli', 'Argostoli', 'Argostoli', 'ionia-nisia', 2, [], { de: 'Hauptort von Kefalonia', en: 'Main town of Kefalonia' }),
  city('kiato', 'Κιάτο', 'Kiato', 'Kiato', 'Kiato', 'peloponnisos', 3),
  city('nea-moudania', 'Νέα Μουδανιά', 'Nea Moudania', 'Nea Moudania', 'Nea Moudania', 'kentriki-makedonia', 3, [], { de: 'Tor zur Chalkidiki', en: 'Gateway to Chalkidiki' }),
  city('chrysoupoli', 'Χρυσούπολη', 'Chrysoupoli', 'Chrysoupoli', 'Chrysoupoli', 'anatoliki-makedonia-thraki', 3, ['Chrysoupolis', 'Hrisoupoli']),
  city('siteia', 'Σητεία', 'Siteia', 'Sitia', 'Sitia', 'kriti', 3, ['Sitia']),
  city('lefkada', 'Λευκάδα', 'Lefkada', 'Lefkada', 'Lefkada', 'ionia-nisia', 2, ['Lefkas'], { de: 'Inselhauptort, per Brücke erreichbar', en: 'Island town reached by a causeway' }),
  city('didymoteicho', 'Διδυμότειχο', 'Didymoteicho', 'Didymoteicho', 'Didymoticho', 'anatoliki-makedonia-thraki', 3, ['Didymoticho', 'Didimoticho']),
  city('kalampaka', 'Καλαμπάκα', 'Kalampaka', 'Kalambaka', 'Kalambaka', 'thessalia', 2, ['Kalabaka'], { de: 'Unterhalb der Meteora-Klöster', en: 'Below the Meteora monasteries' }),
  city('almyros', 'Αλμυρός', 'Almyros', 'Almyros', 'Almyros', 'thessalia', 3, ['Almiros']),
  city('lagkadas', 'Λαγκαδάς', 'Lagkadas', 'Langadas', 'Langadas', 'kentriki-makedonia', 3, ['Lagadas']),
  city('marathonas', 'Μαραθώνας', 'Marathonas', 'Marathon', 'Marathon', 'attiki', 2),
  city('lavrio', 'Λαύριο', 'Lavrio', 'Lavrio', 'Lavrio', 'attiki', 3, ['Lavrion', 'Laurion']),
  city('naxos', 'Νάξος', 'Naxos', 'Naxos', 'Naxos', 'notio-aigaio', 2, [], { de: 'Hauptort der Insel Naxos', en: 'Main town of Naxos' }),
  city('polykastro', 'Πολύκαστρο', 'Polykastro', 'Polykastro', 'Polykastro', 'kentriki-makedonia', 3, ['Polikastro'], { de: 'Nahe der Grenze zu Nordmazedonien', en: 'Near the North Macedonian border' }),
  city('elassona', 'Ελασσόνα', 'Elassona', 'Elassona', 'Elassona', 'thessalia', 3),
  city('karpenisi', 'Καρπενήσι', 'Karpenisi', 'Karpenisi', 'Karpenisi', 'sterea-ellada', 3),
  city('amfissa', 'Άμφισσα', 'Amfissa', 'Amfissa', 'Amfissa', 'sterea-ellada', 3, [], { de: 'Nahe Delphi', en: 'Near Delphi' }),
  city('messini', 'Μεσσήνη', 'Messini', 'Messini', 'Messini', 'peloponnisos', 3),
  city('litochoro', 'Λιτόχωρο', 'Litochoro', 'Litochoro', 'Litochoro', 'kentriki-makedonia', 3, [], { de: 'Ausgangspunkt für den Olymp', en: 'Base for Mount Olympus' }),
  city('alexandreia', 'Αλεξάνδρεια', 'Alexandreia', 'Alexandreia', 'Alexandreia', 'kentriki-makedonia', 3, ['Alexandria']),
  city('sidirokastro', 'Σιδηρόκαστρο', 'Sidirokastro', 'Sidirokastro', 'Sidirokastro', 'kentriki-makedonia', 3, ['Sidhirokastro', 'Siderokastro'], { de: 'An der Straße nach Bulgarien', en: 'On the road to Bulgaria' }),
  city('gastouni', 'Γαστούνη', 'Gastouni', 'Gastouni', 'Gastouni', 'dytiki-ellada', 3),
  city('keratea', 'Κερατέα', 'Keratea', 'Keratea', 'Keratea', 'attiki', 3),
  city('aigina', 'Αίγινα', 'Aigina', 'Aegina', 'Ägina', 'attiki', 3, ['Egina', 'Aegina'], { de: 'Inselhauptort im Saronischen Golf', en: 'Island town in the Saronic Gulf' }),
  city('argos-orestiko', 'Άργος Ορεστικό', 'Argos Orestiko', 'Argos Orestiko', 'Argos Orestiko', 'dytiki-makedonia', 3),
  city('atalanti', 'Αταλάντη', 'Atalanti', 'Atalanti', 'Atalanti', 'sterea-ellada', 3),
  city('istiaia', 'Ιστιαία', 'Istiaia', 'Istiaia', 'Istiea', 'sterea-ellada', 3, ['Istiea']),
  city('aliveri', 'Αλιβέρι', 'Aliveri', 'Aliveri', 'Aliveri', 'sterea-ellada', 3),
  city('kyparissia', 'Κυπαρισσία', 'Kyparissia', 'Kyparissia', 'Kyparissia', 'peloponnisos', 3, ['Kiparissia']),
  city('gytheio', 'Γύθειο', 'Gytheio', 'Gythio', 'Gythio', 'peloponnisos', 3, ['Gythio', 'Githio', 'Gythion']),
  city('filippiada', 'Φιλιππιάδα', 'Filippiada', 'Filippiada', 'Filippiada', 'ipeiros', 3),
  city('kissamos', 'Κίσσαμος', 'Kissamos', 'Kissamos', 'Kissamos', 'kriti', 3, ['Kastelli Kissamou']),
  city('moires', 'Μοίρες', 'Moires', 'Moires', 'Mires', 'kriti', 3, ['Mires']),
  city('karystos', 'Κάρυστος', 'Karystos', 'Karystos', 'Karystos', 'sterea-ellada', 3, ['Karistos']),
];

const region = (
  slug: string,
  native: string,
  translit: string,
  en: string,
  de: string,
  regionType: 'periphery' | 'island',
  tier: 1 | 2 | 3,
  extra: string[] = [],
  hint?: L10n,
): PlaceItem => ({
  id: `el:region:${slug}`,
  kind: 'region',
  native,
  translit,
  names: { en, de },
  accepted: [translit, en, de, ...extra],
  countryId: 'GR',
  regionType,
  tier,
  hint,
});

const ISLAND: L10n = { de: 'Insel', en: 'Island' };

export const REGIONS: PlaceItem[] = [
  // The 13 regions (periphereies) of Greece
  region('attiki', 'Αττική', 'Attiki', 'Attica', 'Attika', 'periphery', 1),
  region('kentriki-makedonia', 'Κεντρική Μακεδονία', 'Kentriki Makedonia', 'Central Macedonia', 'Zentralmakedonien', 'periphery', 1),
  region('anatoliki-makedonia-thraki', 'Ανατολική Μακεδονία και Θράκη', 'Anatoliki Makedonia kai Thraki', 'Eastern Macedonia and Thrace', 'Ostmakedonien und Thrakien', 'periphery', 1,
    ['East Macedonia and Thrace', 'Ostmakedonien-Thrakien']),
  region('dytiki-makedonia', 'Δυτική Μακεδονία', 'Dytiki Makedonia', 'Western Macedonia', 'Westmakedonien', 'periphery', 2, ['West Macedonia']),
  region('ipeiros', 'Ήπειρος', 'Ipeiros', 'Epirus', 'Epirus', 'periphery', 1, ['Ipiros']),
  region('thessalia', 'Θεσσαλία', 'Thessalia', 'Thessaly', 'Thessalien', 'periphery', 1),
  region('ionia-nisia', 'Ιόνια Νησιά', 'Ionia Nisia', 'Ionian Islands', 'Ionische Inseln', 'periphery', 2),
  region('dytiki-ellada', 'Δυτική Ελλάδα', 'Dytiki Ellada', 'Western Greece', 'Westgriechenland', 'periphery', 2, ['West Greece']),
  region('sterea-ellada', 'Στερεά Ελλάδα', 'Sterea Ellada', 'Central Greece', 'Mittelgriechenland', 'periphery', 2),
  region('peloponnisos', 'Πελοπόννησος', 'Peloponnisos', 'Peloponnese', 'Peloponnes', 'periphery', 1, ['Peloponnesos']),
  region('voreio-aigaio', 'Βόρειο Αιγαίο', 'Voreio Aigaio', 'North Aegean', 'Nördliche Ägäis', 'periphery', 2),
  region('notio-aigaio', 'Νότιο Αιγαίο', 'Notio Aigaio', 'South Aegean', 'Südliche Ägäis', 'periphery', 2),
  region('kriti', 'Κρήτη', 'Kriti', 'Crete', 'Kreta', 'periphery', 1),

  // Islands with Street View coverage
  region('kerkyra', 'Κέρκυρα', 'Kerkyra', 'Corfu', 'Korfu', 'island', 1, [], ISLAND),
  region('rodos', 'Ρόδος', 'Rodos', 'Rhodes', 'Rhodos', 'island', 1, [], ISLAND),
  region('lesvos', 'Λέσβος', 'Lesvos', 'Lesbos', 'Lesbos', 'island', 2, [], ISLAND),
  region('chios', 'Χίος', 'Chios', 'Chios', 'Chios', 'island', 2, [], ISLAND),
  region('samos', 'Σάμος', 'Samos', 'Samos', 'Samos', 'island', 2, [], ISLAND),
  region('naxos', 'Νάξος', 'Naxos', 'Naxos', 'Naxos', 'island', 2, [], ISLAND),
  region('santorini', 'Σαντορίνη', 'Santorini', 'Santorini', 'Santorin', 'island', 1, ['Thira', 'Thera'], ISLAND),
  region('mykonos', 'Μύκονος', 'Mykonos', 'Mykonos', 'Mykonos', 'island', 2, [], ISLAND),
  region('kefalonia', 'Κεφαλονιά', 'Kefalonia', 'Kefalonia', 'Kefalonia', 'island', 2, ['Cephalonia', 'Kefallonia'], ISLAND),
  region('zakynthos', 'Ζάκυνθος', 'Zakynthos', 'Zakynthos', 'Zakynthos', 'island', 2, ['Zante'], ISLAND),
  region('evvoia', 'Εύβοια', 'Evvoia', 'Euboea', 'Euböa', 'island', 1, ['Evia', 'Evvia', 'Evoia'], ISLAND),
  region('limnos', 'Λήμνος', 'Limnos', 'Lemnos', 'Limnos', 'island', 3, [], ISLAND),
  region('kos', 'Κως', 'Kos', 'Kos', 'Kos', 'island', 2, [], ISLAND),
  region('thasos', 'Θάσος', 'Thasos', 'Thasos', 'Thasos', 'island', 3, [], ISLAND),
];
